/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class club_younge_jni_Security */

#ifndef _Included_club_younge_jni_Security
#define _Included_club_younge_jni_Security
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     club_younge_jni_Security
 * Method:    decrypt
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_club_younge_jni_Security_decrypt
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     club_younge_jni_Security
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_club_younge_jni_Security_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     club_younge_jni_Security
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_club_younge_jni_Security_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
